Add parental rating fields to EPG, Timers and Recordings (Piers).
kodi-pvr/pvr.demo pull request #164
Opened 2024-08-19 04:29 UTC by DeltaMikeCharlie

Piers replacement for https://github.com/kodi-pvr/pvr.demo/pull/137.
v22.2.0

Add parental rating fields in support of https://github.com/xbmc/xbmc/pull/24096

Access via $INFO[ListItem.ParentalRating], $INFO[ListItem.ParentalRatingCode], $INFO[ListItem.ParentalRatingIcon] and $INFO[ListItem.ParentalRatingSource] respectively.

Note: 'ListItem.ParentalRatingCode' will be available once https://github.com/xbmc/xbmc/pull/23586 has been merged. However, the columns are already in the epgtags table of the PVR/EPG database.

2024-08-20 18:06 UTC, ksooo requested changes
Please remove the timer leftovers. Add-On API does not offer parental rating data fields for timers. This makes no sense as we found out in earlier discussions.

2024-08-20 18:06 UTC, ksooo commented on pvr.demo/changelog.txt
> +- Add support for parentalRating+Code+Icon+Source to EPG, timers and recordings.
Remove "timers", as this is not true.

2024-08-20 18:06 UTC, ksooo commented on pvr.demo/PVRDemoAddonSettings.xml
> +    </timer>
Remove this. We have no parental rating support for timers.

2024-08-20 18:06 UTC, ksooo commented on src/PVRDemo.h
> +  std::string strParentalRatingSource;
Remove this!

2024-08-20 18:06 UTC, ksooo commented on src/PVRDemo.cpp
> +
Remove this.

2024-08-21 01:34 UTC, DeltaMikeCharlie commented on pvr.demo/changelog.txt
> +- Add support for parentalRating+Code+Icon+Source to EPG, timers and recordings.
Done.

2024-08-21 01:35 UTC, DeltaMikeCharlie commented on pvr.demo/PVRDemoAddonSettings.xml
> +    </timer>
Done.

2024-08-21 01:35 UTC, DeltaMikeCharlie commented on src/PVRDemo.h
> +  std::string strParentalRatingSource;
Done.

2024-08-21 01:35 UTC, DeltaMikeCharlie commented on src/PVRDemo.cpp
> +
Done.

2024-08-21 07:35 UTC, ksooo approved these changes

2024-08-21 07:37 UTC, merged